language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-wakanda-project' ]; then cd .. && eval "mv $currentfolder generator-wakanda-project" && cd generator-wakanda-project; fi

